### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by glasgowm148** [paideiadao/paideia-app#119]
Link this video/description somewhere for new users to see? 

To engage with a DAO, you need to connect and authenticate your wallet.
1. Obtain the specific tokens required for the DAO you want to join.
2. During beta, you'll need BPaideia tokens, obtainable from the [Ergo faucet](https://ergofaucet.org/).
3. After [staking](https://app.paideia.im/Sigmanauts/staking/manage) your DAO token, you can participate in actions like voting or proposing changes.

[Paideia, Joining Your DAO | One Take Series](https://youtu.be/YUGNLQ6n8BA)

**Comment by noob77777** [comment]
`Getting Started` link added
