### ISSUE TITLE
Create DAO: Staking Config UI

### ISSUE THREAD

**Issue by noob77777** [paideiadao/paideia-app#130]
- Add Staking Section to Tokenomics in Create DAO

**Comment by noob77777** [comment]
@Luivatra please add descriptions for the fields

```
{
    "stakePoolSize": 0,
    "stakingEmissionAmount": 1,
    "stakingEmissionDelay": 2,
    "stakingCycleLength": 864000000,
    "stakingProfitSharePct": 50,
    "pureParticipationWeight": 25,
    "participationWeight": 25
}
```

**Comment by Luivatra** [comment]
> @Luivatra please add descriptions for the fields
> 
> ```
> {
>     "stakePoolSize": 0,
>     "stakingEmissionAmount": 1,
>     "stakingEmissionDelay": 2,
>     "stakingCycleLength": 864000000,
>     "stakingProfitSharePct": 50,
>     "pureParticipationWeight": 25,
>     "participationWeight": 25
> }
> ```

stakePoolSize: Number of governance tokens to lock into the stake pool, 0 or more
stakingEmissionAmount: Amount of governance tokens distributed to stakers every staking cycle
stakingEmissionDelay: Delay for rewards to be distributed to stakers (staker first gets reward after so many cycles), 1 or more (there is some max but need to calculate, set max to 10 for now)
stakingCycleLength: Length in ms of a staking cycle, reward and profit is shared every cycle
stakingProfitSharePct: amount of dao profit to share with stakers, 0-100
pureParticipationWeight: pct defining how much participation in governance is weighted in reward distribution, 0-100
participationWeight: pct defining how much used votes are weighted in reward distribution, 0-100, these two should not exceed 100 combined. Remaining pct is rewards distributed based on staked amount.
