### ISSUE TITLE
Add support for Ergopay

### ISSUE THREAD

**Issue by ErgoTester** [paideiadao/paideia-app#146]
cannot read properties of undefined (reading 'nautilus')

**Comment by esot321c** [comment]
Vote and staking not supporting Ergopay at this time

**Comment by esot321c** [comment]
Add ergopay support for: 
- Create proposals
- Vote
- Stake

**Comment by noob77777** [comment]
![Image](https://github.com/user-attachments/assets/4fd601a6-918f-472e-a386-9364a42ab630)
