### ISSUE TITLE
The wallet did not contain the tokens required for staking

### ISSUE THREAD

**Issue by moon-miner** [paideiadao/paideia-app#182]
when i try to stake my sig Sigmanauts Mining DAO token i get "The wallet did not contain the tokens required for staking" as the picture shows.
i have the token on my wallet and also its shown bellow amount that i have 1 available tokens to stake "1 SIG available"
![Screenshot_20240925_190055](https://github.com/user-attachments/assets/d9096d7c-8a66-45d5-bbbb-eda5fdad4de3)

**Comment by Jomossey** [comment]
@moon-miner This discrepancy can be confusing. Have you tried refreshing the wallet

**Comment by moon-miner** [comment]
> @moon-miner This discrepancy can be confusing. Have you tried refreshing the wallet

Deleted the wallet from nautilus, restored it from seed phrase, connected it to paideia and still the same issue.

**Comment by Jomossey** [comment]
@moon-miner  It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SIG07638
Please see the link below to our dedicated support line:
[Staking Sig Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by andrehafner** [comment]
> @moon-miner It sounds like your query would be best dealt with by the support team. I'll have to refer you to the official support live chat with the ticket ID SIG07638 Please see the link below to our dedicated support line: [Staking Sig Network DApps Support Ticket Requests.](https://thedappsupport.com/) Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

This is a scammer. Do not do this. Hop in sigs chat or dm me from sigs chat.

**Comment by andrehafner** [comment]
Also people have had luck consolidating and making sure bPaideia and the Sig token are the only things there.

**Comment by moon-miner** [comment]
> Also people have had luck consolidating and making sure bPaideia and the Sig token are the only things there.

Have consolidated and still the same, its the same wallet i use for cyberverse wallet cant left sig dao token alone :S

**Comment by moon-miner** [comment]
I didn't have bpaideia in my wallet :B
