### ISSUE TITLE
DAO Config: auto-create config proposal

### ISSUE THREAD

**Issue by esot321c** [paideiadao/paideia-app#30]
When someone hits "save" on the config page, it should auto-generate a proposal to change that DAO config option.

**Comment by esot321c** [comment]
- [x] Backend 
- [ ] Frontend

**Comment by esot321c** [comment]
1) Add update config action to create proposal
2) Auto-create a proposal when user hits "Save" on config page

**Comment by Luivatra** [comment]
Mapping:
| DAO Config UI field | Config key | Default |
| --- | --- | --- |
| DAO Name | im.paideia.dao.name | |
| DAO URL | im.paideia.dao.url | DAO Name |
| DAO Short Description | im.paideia.dao.desc | |
| Activate optimistic governance | N/A | |
| Activate quadratic voting | N/A | |
| Support needed on single choice voting | im.paideia.dao.threshold |  |
| Quorum | im.paideia.dao.quorum |  |
| Vote Duration | im.paideia.dao.min.proposal.time | |
| Theme | im.paideia.dao.theme | |
| Logo | im.paideia.dao.logo | |
| Banner | im.paideia.dao.banner | |
| Banner enabled | im.paideia.dao.banner.enabled | False |
| Footer | im.paideia.dao.footer | |
| Footer enabled | im.paideia.dao.footer.enabled | False |

**Comment by Luivatra** [comment]
Not all of these fields are in use atm, so when creating a proposal check which fields are present in current config and create an insert or update depending on that

**Comment by esot321c** [comment]
Make it more user readable. 

Current: 

![image](https://github.com/paideiadao/paideia-app/assets/86281023/7b5f4366-ef5d-4012-be2f-530006e9ff89)

Figma: 

![image](https://github.com/paideiadao/paideia-app/assets/86281023/52c9f89c-b66a-4044-94af-258f39befe67)

**Comment by noob77777** [comment]
UX update pending
