### ISSUE TITLE
Comments; Remove emoji and attachment buttons

### ISSUE THREAD

**Issue by AlexisEkici** [paideiadao/paideia-app#47]
If you want to attach a file/image or an emoji to your comment it doesn't open the window when you actually click on those buttons.

**Comment by esot321c** [comment]
![image](https://github.com/paideiadao/paideia-app/assets/86281023/16294add-b61d-49bd-b97a-cf9df2bee7e9)

**Comment by esot321c** [comment]
Remove them, we won't use them!
