### ISSUE TITLE
Unable to partially withdraw staked tokens (cannot read properties of undefined (reading 'data)

### ISSUE THREAD

**Issue by FlyingPig69** [paideiadao/paideia-app#59]
Steps to recreate:
1. Stake 1000 tokens.
2. Attempt to withdraw any partial amount.

Get error message "Cannot read properties of undefined (reading 'data)

I read an earlier issues which was related to a tx being in mempool, i verified there were no pending txs in the mempool for my address.

(Note: I was able to succesfully withdraw all/max amount, issue is restricted to partial unstake)

**Comment by Luivatra** [comment]
Partial unstake is disabled, because it opens up for gaming the staking rewards/profit distribution. So intended behaviour, the error message just isnt too pretty :)

**Comment by Luivatra** [comment]
To do:

- [ ] Remove ability to do partial unstake from frontend

**Comment by FlyingPig69** [comment]
> Partial unstake is disabled, because it opens up for gaming the staking rewards/profit distribution. So intended behaviour, the error message just isnt too pretty :)

How is partial unstake different to unstaking all of it and then restaking a smaller amount?

**Comment by esot321c** [comment]
Bounty: Please remove ability to partially unstake

![image](https://github.com/paideiadao/paideia-app/assets/86281023/b8e943ef-414c-49e9-a728-035f188fda81)


Remove input box, force it to unstake the entire amount. Input box can be there, auto-filled with the amount, but disabled.

**Comment by Luivatra** [comment]
> > Partial unstake is disabled, because it opens up for gaming the staking rewards/profit distribution. So intended behaviour, the error message just isnt too pretty :)
> 
> How is partial unstake different to unstaking all of it and then restaking a smaller amount?

A DAO can have delayed staking/profit rewards so that only those that have staked for a certain amount of time get rewards. Partial unstaking could circumvent this.
