### ISSUE TITLE
Unable to add additional tokens to existing stake

### ISSUE THREAD

**Issue by FlyingPig69** [paideiadao/paideia-app#60]
Steps to recreate:
1. Add 1000 tokens through "Manage Staking" menu. This will succesfully go through.
2. Attempt to add another amount (any amount), this will fail

Error message: "Cannot read properties of undefined (reading 'data')"

**Comment by esot321c** [comment]
To recreate: 

Add stake, submit transaction, add stake again. 

Backend error: {data: 'Not enough erg in wallet for adding stake', status: 400, statusText: 'Bad Request'

Check transaction chaining

**Comment by esot321c** [comment]
New issue more general related to tx chaining

**https://github.com/paideiadao/paideia-app/issues/80**
