### ISSUE TITLE
When posting a discussion and referencing an existing proposal, it's only linked one way

### ISSUE THREAD

**Issue by FlyingPig69** [paideiadao/paideia-app#62]
Steps to recreate:
1. Create a proposal 
2. Then create a discussion and reference the proposal in step 1

**Example:**
Proposal:  
https://paideia-app-git-beta-ergo-pad.vercel.app/Paideia/proposal/a-swinetillating-proposal-lets-make-pigs-fly--3dc89723-5332-48a7-a1ea-e0374d8ddac2

Discusstion: 
https://paideia-app-git-beta-ergo-pad.vercel.app/Paideia/discussion/making-pigs-fly-31f3e8b5-a133-4185-85d2-02cd2bbd07ab?tab=referenced

Result:
The proposal is referenced in the discussion, but the discussion is not referenced in the proposal.

**Comment by FlyingPig69** [comment]
This might actually be expected behaviour since you are creating the reference at the point of submitting proposal/discussion.

Perhaps this is more of a request to change "referenced" to "linked"?

**Comment by esot321c** [comment]
![image](https://github.com/paideiadao/paideia-app/assets/86281023/472fe38e-11a4-4904-95ca-03e10c7f5e4c)

Change wording to "references" and "this discussion has referenced the following X# proposals: "

**Comment by esot321c** [comment]
Also update wording when a proposal references other proposals (discussion and proposals have different names but are essentially all proposals)

**Comment by esot321c** [comment]
It should look like this:

![image](https://github.com/paideiadao/paideia-app/assets/86281023/573f3527-b820-4416-8fca-461e1b0229db)
