### ISSUE TITLE
Non-Userfriendly error message when using non-allowed characters in profile username

### ISSUE THREAD

**Issue by FlyingPig69** [paideiadao/paideia-app#63]
Steps to recreate:
1. Edit your profile username to "Flying_Pig"

Error message: 
"{"detail":[{"loc":["body","name"],"msg":"'Flying_Pig' is not restricted to 'QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890'","type":"value_error"}]}"

Removing the _ enables the name to be saved.

**Comment by esot321c** [comment]
Bounty: improve error messages and form validation visualization

**Comment by svgor-code** [comment]
@esot321c assign me please
