### ISSUE TITLE
UI Proposal: Make activity log links so users can read the actual proposal/discussion

### ISSUE THREAD

**Issue by FlyingPig69** [paideiadao/paideia-app#65]
As it stands, I'll have to manually find the discussion/proposal whereas intuitively I want to click the log entry and get to the discussion/proposal.

![image](https://github.com/paideiadao/paideia-app/assets/124304224/e1d5bd8a-a64e-4e41-990b-4805c818abd9)

**Comment by esot321c** [comment]
Duplicate of https://github.com/paideiadao/paideia-app/issues/18
