### ISSUE TITLE
UI Proposal: Alignment 

### ISSUE THREAD

**Issue by glasgowm148** [paideiadao/paideia-app#69]
Alignment is a little off on a few pages, but most notably the Treasury page. The 'Show Other Fund Sources' button is also a little cramped. 

![Screenshot 2023-10-05 at 11 48 09](https://github.com/paideiadao/paideia-app/assets/19927264/9ebc8fa0-c3fe-4251-8ae1-ee320bd2c78d)

**Comment by svgor-code** [comment]
@esot321c I can fix this
