### ISSUE TITLE
Add minutes/hours/days to vote duration

### ISSUE THREAD

**Issue by esot321c** [paideiadao/paideia-app#76]
When creating a proposal:

![image](https://github.com/paideiadao/paideia-app/assets/86281023/3760cc1d-55fb-4eda-b20a-e8e2571a23e3)

Allow them to choose minutes, hours, or days. It can be a drop down attached

**Comment by piber-dev** [comment]
hello @esot321c

this is already resolved, see picture:

![image](https://github.com/paideiadao/paideia-app/assets/138930882/00368a71-6f50-42e1-b52e-96998d155370)

**Comment by esot321c** [comment]
@piber-dev I think we need to bring this over from the main branch into the beta branch

**Comment by piber-dev** [comment]
this picture is from the beta branch:

![image](https://github.com/paideiadao/paideia-app/assets/138930882/0fc9903b-17ec-4859-a878-7603ba3f9be7)

this is completed

**Comment by esot321c** [comment]
> this picture is from the beta branch:
> 
> ![image](https://github.com/paideiadao/paideia-app/assets/138930882/0fc9903b-17ec-4859-a878-7603ba3f9be7)
> 
> this is completed

You are in the "create Dao" page

The issue is specific to the "create proposal" page
