### ISSUE TITLE
Notifications not marked as "read"

### ISSUE THREAD

**Issue by esot321c** [paideiadao/paideia-app#78]
- Please set it so when you click on a notification, it automatically becomes "read" 
- Currently, when you click "mark all as read" you need to refresh the page to see the notifications are "read"

**Comment by HelixEvo** [comment]
File notifications/index

------------------------

import useSWR, { mutate } from 'swr';

onClick={() =>
    globalContext.api
      ?.markNotificationsAsRead(notifications ? notifications[0].id : 0)
      .then(() => {
            globalContext.metadata.setMetadata({
                ...globalContext.metadata.metadata,
                unreadNotificationCount: 0,
            });

            // Manually updating without re-fetching:
            const updatedNotifications = notifications.map(notification => ({
                ...notification,
                is_read: true
            }));
            mutate(`/notificatons/${globalContext.api?.daoUserData?.id}`, updatedNotifications, false);
      })
      .catch((err) => {
            console.log(err);
      })
}
