### ISSUE TITLE
Improve "error" view

### ISSUE THREAD

**Issue by esot321c** [paideiadao/paideia-app#81]
![image](https://github.com/paideiadao/paideia-app/assets/86281023/9bfcce45-f57e-417c-9ff9-cce92d36a06e)

Make a centered error message, something like: 

"Error: this page is currently unavailable due to a server issue. Please wait a few moments and try again" 

Here's an example of how it could look: 

![image](https://github.com/paideiadao/paideia-app/assets/86281023/6b9cd1be-351f-40fd-b2e9-d659aabf66a4)

**Comment by JoaoFGuiomar** [comment]
@esot321c I can't seem to assign myself to this issue

**Comment by esot321c** [comment]
> @esot321c I can't seem to assign myself to this issue

Got it, thanks! Updated the instructions for everyone as well (contact me to be assigned an issue)
