### ISSUE TITLE
Create proposals should automatically display the first "choose an action" 

### ISSUE THREAD

**Issue by esot321c** [paideiadao/paideia-app#84]
![image](https://github.com/paideiadao/paideia-app/assets/86281023/9a419125-7148-4d2d-bd19-770bf80a9331)

If this is the first action, it should automatically just show this screen: 

![image](https://github.com/paideiadao/paideia-app/assets/86281023/8a7d6e3a-f822-49a6-bb40-4363e7f74b60)

**Comment by esot321c** [comment]
Once the first action is selected, then "add another action" can appear

**Comment by thesloppyguy** [comment]
@esot321c Made a pull request for this issue. Please review when possible.

**Comment by esot321c** [comment]
Adding this comment here too: 


@thesloppyguy there is still one issue. The "add another action" doesn't activate once you've selected what type of action the first one will be.

**Comment by thesloppyguy** [comment]
@noob77777 can you explain why [this ](https://github.com/paideiadao/paideia-app/blob/2506208b6550dd02ac92e0997087fe294ac3b9a6/components/dao/proposal/ProposalVote.tsx#L91C15-L91C15) condition is being checked. This is the reason for the issue mentioned by @esot321c and you seem to have committed to this last. 
```
disabled={context?.api?.value?.actions?.length >= 1}
```
